spring:
  # 配置数据源信息
  datasource:
  # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.129:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置类型别名所对应的包
  type-aliases-package: tech.snnukf.mybatisplusspringboot.pojo;
  # 扫描通用枚举的包
  type-enums-package: tech.snnukf.mybatisplusspringboot.enums